### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Romvnly-Gaming** [zephyrkul/FluffyCogs#10]
i have used the rift cog and it doesn't work, i have all the permissions setup correctly because if i didn't the bot wouldn't be able to respond https://i.imgur.com/Op0iTKJ.png https://i.imgur.com/9YiVFHa.png https://i.imgur.com/qKU6FLx.png

**Comment by Romvnly-Gaming** [comment]
for some reason it works now.

**Comment by zephyrkul** [comment]
Happy to see it worked out for you.
