### ISSUE TITLE
[Request] secureinv added tracking.

### ISSUE THREAD

**Issue by cry8wolf9** [zephyrkul/FluffyCogs#12]
In Trusty's modlog it tracks the creation of the invite as shown [Here](https://cdn.discordapp.com/attachments/635319212918964225/706707381597241364/invCreate.PNG) fine.
However it does not track if you add a reason as shown [Here](https://cdn.discordapp.com/attachments/635319212918964225/706708055391338586/invCommand.PNG)
Is it possible to somehow get the reason logged?

**Comment by zephyrkul** [comment]
Logging is not handled by this cog. It is up to the cog that does that logging to log provided reasons.
