### ISSUE TITLE
bot owner relays message twice.

### ISSUE THREAD

**Issue by Dallezh** [zephyrkul/FluffyCogs#13]
Hi.

The bot seems to relay the message of the owner twice.
https://bit.ly/2ZSJfNW again it only happens whenever I send a message, works just fine for everyone else.

**Comment by zephyrkul** [comment]
Unable to duplicate, and I just pushed #18 (Rift rework) recently which should™️ have fixed this regardless. If you still have this issue after 5b26bdb5aba2925449f85a727ce499794611f8d9, please re-open this and let me know.
