### ISSUE TITLE
automatic rift closing.

### ISSUE THREAD

**Issue by Dallezh** [zephyrkul/FluffyCogs#14]
Not sure if this is an issue or not, but the bot seems to automatically unlink the rifts after a few days, so I have to relink the servers again.

**Comment by zephyrkul** [comment]
The only circumstance that would happen is if either the destination closes the rift on their end, the cog is reloaded, or the bot shuts down, as rifts do not persist through reloads. Are any of these the case?

**Comment by Dallezh** [comment]
ah that could probably have been the case ye, I believe I had to restart to update java earlier, so might have been the reason then.

**Comment by Dallezh** [comment]
ah, No it happen over night, now that I think about it, when I woke up the rifts were closed, and I didn't restart the bot or the server, so I don't think so no.

**Comment by zephyrkul** [comment]
The scenarios listed above are the only scenarios where such an event could ever happen, beyond severe memory corruption which would break down the entire bot.
