### ISSUE TITLE
[Rift] Improve strings in `[p]rift link` and `[p]rift open`

### ISSUE THREAD

**Issue by jack1142** [zephyrkul/FluffyCogs#29]
`[p]rift link` and `[p]rift open` have exactly same help docstrings and messages sent by both of the commands are also exactly the same, which makes it hard to figure out the difference between the two without testing.

**Comment by zephyrkul** [comment]
Follow up request from the same individual: option to prepend author information even when the author is the bot owner.

**Comment by zephyrkul** [comment]
Resolved with a0932921a9e15bd14ee519114da13386879f6a68.
