### ISSUE TITLE
[Invoice cog] Permissions don't update correctely

### ISSUE THREAD

**Issue by bastienroussel** [zephyrkul/FluffyCogs#38]
Hello,

I use your cog on my server and when I create a new channel the permissions are not right :/ everybody have access to it instead of the role created dynamically.
![image](https://user-images.githubusercontent.com/52447846/96161285-5cc4d500-0f17-11eb-88a6-f3a455eebbc2.png)

Thanks for your time 👍

**Comment by zephyrkul** [comment]
Unable to replicate. Could you answer the following questions?

1) What permissions does your bot have in the server?
2) What permissions does your bot have in the category you are creating a new voice channel in?
3) Do any errors appear in your console or logs when you attempt to create the new channel?

**Comment by bastienroussel** [comment]
1 and 2 He have full permission on the server and this category 
3. I dont have any lors
This bug it's since I have updated to the last version of red and I have try with first version of your cog and it's work but with the lastet he doesn't work anymore :/

**Comment by zephyrkul** [comment]
What other cogs do you have loaded? It's possible that some other cog is interfering with invoice's attempts to set permissions up.

You can check what cogs you have loaded using the `[p]cogs` command

**Comment by bastienroussel** [comment]
![image](https://user-images.githubusercontent.com/52447846/96299896-04640500-0ff5-11eb-9246-ac5ba1a6cafd.png)

**Comment by zephyrkul** [comment]
Of the cogs I know of in that list, none should interfere with invoice. I have, however, never heard of a cog called `crier` and can't find such a cog in the cogs listing.

Could you also check your server's audit logs for when the bot creates the role and channel?

**Comment by zephyrkul** [comment]
Did you manage to find the cause and fix it yourself?

**Comment by bastienroussel** [comment]
I have delete all data concerning invoice cog
