### ISSUE TITLE
invoice: dynamic docstring needs an update

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [zephyrkul/FluffyCogs#39]
allow customisation of default permissions like allowing **view history** and **link**/**image sharing**

maybe a new settings tab in your commands menu with toggles for certain sain permissions like the one above miss out obvious no go permissions like manage and stuff but allow basic ones that normal users could require

**Comment by zephyrkul** [comment]
Invoice attempts to inherit permissions from the category the dynamic channel is created in, so just enable the permissions you need in the category and the new channel should have that permission active.
If you have a guild-wide role set, the dynamic channel's role will also inherit its permissions.

**Comment by XxMr1234GamerzxX** [comment]
ah cool didn't know that thank you

**Comment by zephyrkul** [comment]
I'll put a note about it in the docstring somewhere so it's more well-known.

**Comment by zephyrkul** [comment]
Keeping this open so I don't forget to update the docstring.

**Comment by XxMr1234GamerzxX** [comment]
ah okay
