### ISSUE TITLE
Rift Request: Forward all messages from source

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [zephyrkul/FluffyCogs#4]
Hello, 

Is there any chance you could update rift, so that it relays every message from the chat, not just the creator of the rift. Also, to send the name of the user, and possible but not needed user avatar. So that server chats can be fully connected?

**Comment by zephyrkul** [comment]
First one is a common request so most likely I'll add a `[p]rift link` command for such a use case.
As for the latter request, the bot always sends the name of the user except in the sole case that the bot owner opened the rift, in which case the owner's messages will not have their name prepended.

As for sending the user avatar, that would only reasonably be possible by sending embeds in every message. While I'm not against embeds as a concept (my other cogs use them quite liberally) I don't wish to use them for cogs like Rift that send out many messages.

**Comment by zephyrkul** [comment]
Reopening since I'm working on this now.
