### ISSUE TITLE
[invoice] Not adding roles to users without speaking permissions.

### ISSUE THREAD

**Issue by Lewimaron** [zephyrkul/FluffyCogs#45]
I've set everything up as shown here;

![image](https://user-images.githubusercontent.com/24374768/102833463-185b2700-43e9-11eb-89b1-4da4a00198c0.png)

When I, or any other admins, join the channel the role is added correctly. However, when any other user who's deafened joins it's not added to them.

**Comment by zephyrkul** [comment]
The reason is due to the Mute and Deaf options being enabled. This tells the bot not to add the role when the user is server muted or server deafened, which they are when they join a channel they don't have permissions for.

Disable those settings and it will work as you intend.

**Comment by Lewimaron** [comment]
I've just switched the options to false as shown here:

![image](https://user-images.githubusercontent.com/24374768/102833820-1a71b580-43ea-11eb-801b-7dad22b45f37.png)

The confirmation says it now won't modify permissions for muted users and it still doesn't work.
