### ISSUE TITLE
[invoice] Still not adding roles to users without speaking permissions.

### ISSUE THREAD

**Issue by Lewimaron** [zephyrkul/FluffyCogs#46]
Hi,
I opened an issue a few days ago (#45) about invoice not adding roles to users without speaking permission in the channel. You suggested changing the mute and deaf options to false, however this didn't solve the issue.
I asked in the cog support Discord channel and was advised to open a new issue.

I've now tried with both settings set to true and false, as well as each combination of them, however nothing seems to be working.

@everyone has no permissions set in the channel overrides, and everything disabled in the global server permissions.

@members is our normal user role and has connect and speak permissions enabled in the global settings, but speak denied in the channel overrides.

**Comment by zephyrkul** [comment]
Do not file duplicate issues. Re-open the old issue if it's still an issue. I have not had time to look into the issue because, *in case you somehow haven't noticed*, it's the holiday season.

Continue to spam my repo with duplicates and I will block you from filing any further issues.
