### ISSUE TITLE
[Rift] Cannot select between identically named channels

### ISSUE THREAD

**Issue by ax5nonymous** [zephyrkul/FluffyCogs#48]
When using the command:
`.rift open true general`

I get the response:
```
Multiple results found. Choose a destination:


0: general (################), in Server1
1: general (################), in Server2
2: general (################), in Server3
```

Typing any number gives no response, same with the full name, ID number, server name, etc. Typing the number in the initial command still results in the same prompt.

**Comment by zephyrkul** [comment]
fixed with abc532a

run `[p]cog update rift` to update

thanks for the report
