### ISSUE TITLE
[invoice] Permissions do not apply if the user cannot speak.

### ISSUE THREAD

**Issue by VoidNulll** [zephyrkul/FluffyCogs#50]
# User cannot speak, InVoice does not apply permissions

## Description
When the user does not have permissions to speak the InVoice cog will treat the user as AFK and remove the guild role, resets the atc, and atc_overs to None. This happens whenever a user is server muted or does not have permission to speak in a channel.

## A fix
If discord says the user/voice state is afk and is not in a voice channel
- treat the user as AFK and remove the role, atc, and atc_overs

If discord says the user/voice state is AFK and there is a voice channel as well as a guild AFK channel.
- If the AFK channel and voice state channel IDs are equal treat the user as AFK.
- If one of these conditions is false do not treat the user as AFK. (ex: no AFK channel, ids do not match)

## Example code
```py
is_afk_channel = False
# Ensure the voice channel and afk channel exist before assignment.
if a.channel is not None and a.channel.guild.afk_channel is not None:
    # Check if the channel is the set afk channel
    is_afk_channel = a.channel.guild.afk_channel.id == a.channel.id
if not a.channel:  # If there is no vc remove the role.
    role_set.discard(guild_role)
    atc, atc_overs = None, None
elif a.afk and is_afk_channel:  # Check if the user is afk. Remove role if so.
    role_set.discard(guild_role)
    atc, atc_overs = None, None
```

Sourced from VoidNulll@e6d50c20f8600848284c0fab587f00d872e12c1b

This issue may potentially address #45

**Comment by zephyrkul** [comment]
Absurdly enough... this seems to be the reason behind #45.

I damn well looked everywhere for the source of that error when I first found out about it. For whatever reason, [the docs outright lie.](https://discordpy.readthedocs.io/en/stable/api.html#discord.VoiceState.afk) The `afk` attribute has nothing at all to do with the guild's AFK channel, and instead is simply an alias for the [`suppress` attribute](https://discordpy.readthedocs.io/en/stable/api.html#discord.VoiceState.suppress) (which also lies about what it is).
This aliasing can be seen [here.](https://github.com/Rapptz/discord.py/blob/v1.7.2/discord/member.py#L100-L103)

There are various issues I have with how your code handles checking for an afk channel, so I won't be implementing it as you do, but thank you for taking the time to find out this strange issue with the `afk` attribute. I don't know what caused this sudden change, but I suppose I'll have to stop relying on those attributes.
