### ISSUE TITLE
[Spoilerer] Include file previews automatically attached via URLS in the message

### ISSUE THREAD

**Issue by Danstr5544** [zephyrkul/FluffyCogs#56]
As titled really, allow URLs to count as "attached" files, in effect, so that mobile users can spoiler, say, youtube videos.

**Comment by zephyrkul** [comment]
Users can do this already by surrounding the URLs with `||spoiler markdown||`. The spoilerer cog is meant to replicate a feature available in desktop clients to mobile clients, as Discord doesn't have the spoiler option for uploaded files. Mobile users are perfectly capable of spoilering URLs already.

**Comment by Danstr5544** [comment]
Not all users are aware that in order for that to be effective, they need to include spaces within the spoiler tag - that was the reason I brought it up. But fair enough
