### ISSUE TITLE
[Dev] extra dev env vars

### ISSUE THREAD

**Issue by sravan1946** [zephyrkul/FluffyCogs#57]
The extra dev env vars which gets added by other cogs gets reset when loading the Dev cog. Have to restart the bot with the cog unloaded to get all the env vars back.

before loading the cog:
![how it should be](https://user-images.githubusercontent.com/57430307/151158819-9efb65eb-693c-4aef-afa5-c1f12c6b5444.png)

after loading the cog:
![Screenshot 2022-01-26 172001](https://user-images.githubusercontent.com/57430307/151159138-eaa8ff98-e0e6-4e1a-91d5-3770d34e9860.png)

after unloading without restart:
![Screenshot 2022-01-26 172020](https://user-images.githubusercontent.com/57430307/151159185-0a9fe4fb-cc1b-47a1-8b78-7d79a8ef2eb8.png)

**Comment by zephyrkul** [comment]
Thank you for the report, this should be fixed now with https://github.com/zephyrkul/FluffyCogs/commit/9904b5482fc8af080f405d1449a4c1bc5565cbac
