### ISSUE TITLE
[OneTrueSlash] [dpy2] Search Returns Unrelated Commands

### ISSUE THREAD

**Issue by TwinDragon** [Zephyrkul/FluffyCogs#60]
This is somewhat recent with `OneTrueSlash`, but it appears for a bit now, the search portion is always returning three commands without fail: `test`, `cat`, and `dog` when my bot actually doesn't have any cogs that have those commands.

This occurs no matter which command is used, such as `help`, or `cog`, etc... I'll leave the image of running a couple debug commands showing the non-existent command for `cat`.
![image](https://user-images.githubusercontent.com/4114117/167279819-adc3f5e1-7672-4a84-8e36-fb412468d7b5.png)

**Comment by zephyrkul** [comment]
Which version of Red are you on? Bare `v3/develop`?

**Comment by TwinDragon** [comment]
At the time of the issue, this is the version string: `3.5.0.dev191+gec556224` which is the latest from the `v3/develop` repo.
