### ISSUE TITLE
Onedit: This cog requires different Red version than you currently have (3.5.1)

### ISSUE THREAD

**Issue by arjunsatarkar** [Zephyrkul/FluffyCogs#69]
```
!cog install fluffycogs onedit
```
```
This cog requires different Red version than you currently have (3.5.1): onedit (Minimum: 3.1.6, at most: 3.5.0.dev0)
```

Hopefully this is just a matter of specifying the higher max version (given that 3.5.0dev0 is supported)?

**Comment by Zephyrkul** [comment]
All cogs on the master branch are currently forcibly version-locked since they don't support the new Red version - if I removed that requirement, it wouldn't change the fact that the cog would not load.
