### ISSUE TITLE
[LogsFrom] Load A Saved .md File

### ISSUE THREAD

**Issue by LGACode** [zephyrkul/FluffyCogs#8]
Please add a command to load a saved .md file so that a channel can be archived into a file, deleted, then restored later if needed.

**Comment by zephyrkul** [comment]
I gave some thought to this and have decided not to implement this. Simply uploading the .md file to the new channel should be sufficient enough for most use cases, and I'm hesitant to so heavily saturate the bot's rate limit from reposting potentially thousands of messages at once.
