### ISSUE TITLE
Shared libs removal in 3.5

### ISSUE THREAD

**Issue by Dav-Git** [zephyrkul/FluffyCogs#9]
Got a message on 3.2 upgrade that some of the libs used here will be removed with 3.3.
![grafik](https://user-images.githubusercontent.com/57032623/72204067-42376a00-3474-11ea-89ce-f7dc8815c699.png)

**Comment by Dav-Git** [comment]
Title changed because well... we're at 3.3.0 last I checked they're marked for 3.4 now

**Comment by zephyrkul** [comment]
Resolved with https://github.com/zephyrkul/FluffyCogs/compare/e1a667bbc0312916978dfcb4f6e8548c5ca444fa...c93f8412e76de67b7084958bb25f0ab7a73999dd
